export enum TeamComponentsActionTypes {
  ADD_COMPONENT = 'ADD_COMPONENT',
  DELIVER_COMPONENT = 'DELIVER_COMPONENT',
  UPDATE_MODULE_IN_INTEGRATOR_COMPONENT = 'UPDATE_MODULE_IN_INTEGRATOR_COMPONENT',
  UPDATE_DESCRIPTION_IN_INTEGRATOR_COMPONENT = 'UPDATE_DESCRIPTION_IN_INTEGRATOR_COMPONENT'
}
